name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version:  12.x
    
    - name: Move for dir base backend
      run:  cd backend
    
    - name: Install dependencies
      run:  yarn
    
    - name: Move for dir root
      run:  cd ..
    
    - name: Move for dir base frontend
      run: cd frontend
        
    - name: Install dependencies
      run:  yarn
      
    - name: Move for dir root
      run:  cd ..
    
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~app/mopa"

    - name: Install dependencies on Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/mopa/backend
          yarn
          yarn build
          yarn sequelize db:migrate
          yarn sequelize db:seed:all
          pm2 restart server
          cd ~/app/mopa/frontend
          yarn build
          yarn start
          
